version: "3.9"

services:  
  server:
    build: .
    ports:
      - '3000:3000'
    # depends_on:
    #   - db
    volumes:
      - ./src:/app/src
    command: npm run dev:server

volumes:
  postgres_data: